version: "3.6"

services:
  nginx:
    image: nginx:latest
    volumes:
    - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
    - 8000:8000
  php:
    build:
      context: api
    volumes:
      - ./api:/app
    depends_on:
      - nginx
      - db
  web:
    build:
      context: web
    volumes:
    - ./web:/app
    ports:
    - 8080:3000
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'race_vote_db'
      MYSQL_USER: 'tony'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    volumes:
    - ./db:/var/lib/mysql
volumes:
  db: